### ISSUE TITLE
Plugin idea: Apollo-compat Automatic Persisted Query

### ISSUE THREAD

**Issue by cometkim** [graphql-hive/envelop#496] opened 2021-07-27 13:12 UTC
I saw a plugin for parse caching is exist, but it would be better if we have plugin that compat with the Apollo's automatic persisted query protocol a.k.a APQ

Spec: https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine
Apollo: https://www.apollographql.com/docs/apollo-server/performance/apq/
URQL: https://formidable.com/open-source/urql/docs/advanced/persistence-and-uploads/#automatic-persisted-queries

**Comment by ccollie** [comment] 2021-08-08 16:12
I needed this for a project, so I started taking a stab on an implementation based on `Mercurius`. If I have time in the next few days I'll do some cleanup and post my repo.

**Comment by ccollie** [comment] 2021-08-14 22:27
Quick question. Would it be useful to have a distributed cache for this (like `redis`), or would `in-memory` suffice.  I'm supporting the simplest case since currently the former is not possible afaics since `onParse` is synchronous only.

**Comment by ccollie** [comment] 2021-08-14 22:31
Also, despite the name, the code can equally handle `mutations`. Should we restrict to `query` to maintain parity with `apollo-client` ?

**Comment by cometkim** [comment] 2021-08-15 10:35
I'm using some in-memory LRUs and some MongoDB in production. Obviously, this asynchronous situation is needed, but there is still an ongoing discussion about it.

See https://github.com/dotansimha/envelop/discussions/497

**Comment by ccollie** [comment] 2021-08-18 04:29
Here's my initial implementation:

https://github.com/ccollie/envelop/commit/35918f1a75a0e3bfe7cd4684637ff7107c535874

The issue is that per protocol, `query` can be undefined

https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine

so there's no good way (that I know of) for me to test that scenario. The work is done in `onParse` which requires a defined `source`

Any suggestions ?

**Comment by PabloSzx** [comment] 2021-08-24 22:04
Already available for graphql-ez 🎉 (which uses Envelop at it's core, it just hasn't been fully announced yet) https://www.graphql-ez.com/plugins/automatic-persisted-queries 

thank you @ccollie

**Comment by YassinEldeeb** [comment] 2022-12-09 07:48
Closing in favour of the built-in [Automatic Persisted Queries](https://the-guild.dev/graphql/yoga-server/docs/features/automatic-persisted-queries) plugin in GraphQL Yoga v3 🎉

**Closed as completed by YassinEldeeb** 2022-12-09 07:48 UTC
Labels: kind/enhancement
