### ISSUE TITLE
[/sentry]: track stages other than `execute`

### ISSUE THREAD

**Issue by dotansimha** [graphql-hive/envelop#125] opened 2021-04-23 17:11 UTC
probably for the entire pipeline.

**Comment by dotansimha** [comment] 2021-06-13 17:25
Should be possible after doing: https://github.com/dotansimha/envelop/pull/276

**Comment by YassinEldeeb** [comment] 2022-12-08 10:26
since the mentioned PR has been merged then I suppose the issue is resolved. please re-open it if the issue is still relevant.

**Closed as completed by YassinEldeeb** 2022-12-08 10:26 UTC
Labels: good first issue, kind/enhancement
